import '@fullcalendar/common/main.css';
import '@fullcalendar/daygrid/main.css';
import '@fullcalendar/timegrid/main.css';
import '../styles/globals.css';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import { NotificationProvider } from '@web3uikit/core';
//import { ApolloProvider, ApolloClient, InMemoryCache } from '@apollo/client';
import { chain, configureChains, createClient, WagmiConfig, useNetwork } from 'wagmi';
import { publicProvider } from 'wagmi/providers/public';
import { getDefaultWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { bscTestnet } from '../constants/bscTestnetChain';
import { QueryClient, QueryClientProvider } from 'react-query';
import { MoralisProvider } from 'react-moralis';

/*const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  uri: 'https://api.studio.thegraph.com/query/34130/lovetokengorliv7/0.0.4'
});*/

const { chains, provider } = configureChains([chain.polygonMumbai, bscTestnet], [publicProvider()]);
const { connectors } = getDefaultWallets({ appName: 'Mint Your Love', chains });
const wagmiClient = createClient({ autoConnect: true, connectors, provider });
const queryClient = new QueryClient();;

const APP_ID_BSC = process.env.NEXT_PUBLIC_APP_ID_BSC;
const SERVER_URL_BSC = process.env.NEXT_PUBLIC_SERVER_URL_BSC;

const APP_ID_MUMBAI = process.env.NEXT_PUBLIC_APP_ID_MUMBAI;
const SERVER_URL_MUMBAI = process.env.NEXT_PUBLIC_SERVER_URL_MUMBAI;

function MyApp({ Component, pageProps }) {
  const { chain: connectedChain } = useNetwork();
  //console.log('connectedChain ', connectedChain);

//appId={connectedChain?.id === 80001 ? APP_ID_MUMBAI : APP_ID_BSC} serverUrl={connectedChain?.id === 80001 ? SERVER_URL_MUMBAI : SERVER_URL_BSC}
  return (
    <>
      <Head>
        <title>Mint Your Love</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <WagmiConfig client={wagmiClient}>
        <RainbowKitProvider chains={chains}>
          {/*<ApolloProvider client={apolloClient}>*/}
          <MoralisProvider appId={connectedChain?.id === 80001 ? APP_ID_MUMBAI : APP_ID_BSC} serverUrl={connectedChain?.id === 80001 ? SERVER_URL_MUMBAI : SERVER_URL_BSC} >
            <QueryClientProvider client={queryClient}>
              <NotificationProvider>
                <Navbar />
                <Component {...pageProps} />
              </NotificationProvider>
            </QueryClientProvider>
          </MoralisProvider>
          {/*</ApolloProvider>*/}
        </RainbowKitProvider>
      </WagmiConfig>
    </>
  );
}

export default MyApp;