import '@fullcalendar/common/main.css';
import '@fullcalendar/daygrid/main.css';
import '@fullcalendar/timegrid/main.css';
import '../styles/globals.css';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import { NotificationProvider } from '@web3uikit/core';
//import { ApolloProvider, ApolloClient, InMemoryCache } from '@apollo/client';
import { chain, configureChains, createClient, WagmiConfig, useNetwork } from 'wagmi';
import { publicProvider } from 'wagmi/providers/public';
import { getDefaultWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { bscTestnet } from '../constants/bscTestnetChain';
import { QueryClient, QueryClientProvider } from 'react-query';

/*const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  uri: 'https://api.studio.thegraph.com/query/34130/lovetokengorliv7/0.0.4'
});*/

const { chains, provider } = configureChains([chain.polygonMumbai, bscTestnet], [publicProvider()]);
const { connectors } = getDefaultWallets({ appName: 'Mint Your Love', chains });
const wagmiClient = createClient({ autoConnect: true, connectors, provider });
const queryClient = new QueryClient();;

function MyApp({ Component, pageProps }) {

  return (
    <>
      <Head>
        <title>Mint Your Love</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <WagmiConfig client={wagmiClient}>
        <RainbowKitProvider chains={chains}>
          {/*<ApolloProvider client={apolloClient}>*/}
          <QueryClientProvider client={queryClient}>
            <NotificationProvider>
              <Navbar />
              <Component {...pageProps} />
            </NotificationProvider>
          </QueryClientProvider>
          {/*</ApolloProvider>*/}
        </RainbowKitProvider>
      </WagmiConfig>
    </>
  );
}

export default MyApp;